### ISSUE TITLE
Error "handle_call_service" when using keba.start service call 

### ISSUE THREAD

**Issue by fuchsbau123** [dannerph/homeassistant-keba#29]
Hi,
I am using the latest version of the (beta) Keba wallbox integration from HACS and Home Assistant 2024.1.6.
I need different RFID cards to authorize charging and based on the documentation the build-in integration Keba Wallbox can only support one RFID card.
I get the following error, when I use the keba.start service call with an RFID:

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/keba/__init__.py", line 108, in execute_service
host = config_entry.data[CONF_HOST]
~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'host'
2024-03-26 00:13:05.925 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140543036198336] 'host'
```
I can still start the charging with the physical RFID cards on the wallbox (KEBA P30-X).
After some restarts of Home Assistant and the wallbox the error disappears.

Any idea how to solve it?

**Comment by dannerph** [comment]
Hi @fuchsbau123 sorry for the late response, I would guess you need to remove and re-add your charging station. It seems, that there is something wrong with your config entry. (sorry for this issue). If the problem is still persistant, please reopen the issue.
